Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2018-06, with the labels that each got.

#256 RHEV SSH Keypair auth always returns true
  app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
Labels: blocker, gaprindashvili/yes

#257 Use Graph refresh by default
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_template_disconnect_spec.rb
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_target_template_disconnect.yml
Labels: blocker, gaprindashvili/yes

#259 Use Graph refresh by default
  config/settings.yml
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_template_disconnect_spec.rb
Labels: blocker, gaprindashvili/yes

#260 Fix travis network id nil
  app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
Labels: blocker, gaprindashvili/yes

#252 Persister: InventoryCollection building through add_collection()
  app/models/manageiq/providers/redhat/inventory/persister.rb
  app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_collections.rb
  app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_group/cluster_collections.rb
  app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_group/datacenters_collections.rb
  app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_group/hosts_collections.rb
  app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_group/networks_collections.rb
  app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_group/storagedomains_collections.rb
  app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_group/vms_collections.rb
  app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_group/vms_dependency_collections.rb
  app/models/manageiq/providers/redhat/inventory/persister/definitions/network_collections.rb
  app/models/manageiq/providers/redhat/inventory/persister/infra_manager.rb
  app/models/manageiq/providers/redhat/inventory/persister/network_manager.rb
  app/models/manageiq/providers/redhat/inventory/persister/target_collection.rb
  app/models/manageiq/providers/redhat/inventory_collection_default/infra_manager.rb
  app/models/manageiq/providers/redhat/inventory_collection_default/network_manager.rb
Labels: unmergeable

#262 Fix refresh failing on guest device lan collection
  app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
Labels: blocker, bug, gaprindashvili/yes

#265 Use the same assoc for targeted and full refresh
  app/models/manageiq/providers/redhat/inventory/persister/target_collection.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_custom_attributes_spec.rb
Labels: bug

#264 Fix vm targeted refresh on removal
  app/models/manageiq/providers/redhat/inventory/collector/target_collection.rb
  app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_graph_target_vm_spec.rb
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_removal.yml
Labels: blocker, bug, gaprindashvili/yes

#269 [GAPRINDASHVILI] fix miq custom attributes deleted
  app/models/manageiq/providers/redhat/inventory/persister/target_collection.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_custom_attributes_spec.rb
Labels: blocker, bug
