Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2018-05, with the labels that each got.

#236 [GAPRINDASHVILI] [Changelog] Update for gaprindashvili-3 release
  CHANGELOG.md
Labels: documentation

#225 [Changelog] Update for Sprint 80
  CHANGELOG.md
Labels: documentation

#240 Improve performance of EmsFolders and EmsClusters child save blocks
  app/models/manageiq/providers/redhat/inventory_collection_default/infra_manager.rb
Labels: performance

#243 [GAPRINDASHVILI] Fix spec failures with connection vcr
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresh_recording_modifier_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_huge_async_spec.rb
  spec/support/modify_refresh_yml_recording.rb
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_recording_for_mod.yml
Labels: test

#244 Ems metadata improvements
  app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
  app/models/manageiq/providers/redhat/inventory/persister/infra_manager.rb
  app/models/manageiq/providers/redhat/inventory/persister/target_collection.rb
  app/models/manageiq/providers/redhat/inventory_collection_default/infra_manager.rb
Labels: performance

#241 Fix refreshing targeted vm after snapshot removal
  app/models/manageiq/providers/redhat/inventory/collector/target_collection.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_graph_target_vm_spec.rb
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_deleted_snapshot.yml
Labels: blocker, gaprindashvili/yes

#254 Profile description
  app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
  app/models/manageiq/providers/redhat/infra_manager/provision_workflow.rb
  spec/models/manageiq/providers/redhat/infra_manager/provision/configuration/network_spec.rb
Labels: blocker, gaprindashvili/yes

#255 Fix logging oVirt event in debug level
  app/models/manageiq/providers/redhat/infra_manager/event_parsing/parser.rb
Labels: bug, fine/yes, gaprindashvili/yes
