Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2018-12, with the labels that each got.

#317 [Changelog] Update for Sprint 100
  CHANGELOG.md
Labels: documentation

#320 Change FactoryGirl to FactoryBot
  spec/models/manageiq/providers/redhat/infra_manager/disk_attachment_builder_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/event_catcher/runner_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/event_parser_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/host_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/inventory/strategies/v4_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/metrics_capture_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/operations/snapshot_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/provision/configuration/network_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/provision/configuration_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/provision/disk_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/provision/placement_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/provision/state_machine_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/provision_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/provision_via_iso/state_machine_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/provision_via_iso_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/provision_via_pxe/state_machine_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/provision_via_pxe_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/provision_workflow_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/parse/parser_builder_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresh_after_publish_vm_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresh_recording_modifier_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_3_1_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_graph_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_custom_attributes_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_graph_target_template_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_graph_target_vm_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_huge_async_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_host_4_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_template_disconnect_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_vm_4_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_vm_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/vm/reconfigure_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/vm_import_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/vm_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager_spec.rb
  tools/generate_refresh_template_spec.rb
Labels: dependencies, gaprindashvili/no, hammer/no

#319 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-7
  CHANGELOG.md
Labels: documentation

#322 Scope EmsFolder and ResourcePool queries by ems_id
  app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_group/vms_dependency_collections.rb
Labels: bug

#324 [GAPRINDASHVILI] Scope EmsFolder and ResourcePool queries by ems_id
  app/models/manageiq/providers/redhat/inventory_collection_default/infra_manager.rb
Labels: blocker, bug

#311 EMS validation with maintenance zone specs fix
  spec/models/manageiq/providers/redhat/infra_manager/provision/configuration_spec.rb
Labels: hammer/yes

#325 [Changelog] Update for Sprint 101
  CHANGELOG.md
Labels: documentation

#326 Bump master travis.yml to ruby 2.4.5
  .travis.yml
Labels: test

#316 Fix targeted host refresh
  app/models/manageiq/providers/redhat/inventory/collector/target_collection.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_graph_target_host_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_host_4_spec.rb
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_host.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_target_host.yml
Labels: blocker, bug, hammer/yes
