Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2018-04, with the labels that each got.

#232 Fix provider discovery
  app/models/manageiq/providers/redhat/discovery.rb
Labels: blocker, bug, gaprindashvili/yes

#230 Properly fetch snapshot current state
  app/models/manageiq/providers/redhat/infra_manager/refresh/parse/strategies/vm_inventory.rb
  app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_graph_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_spec.rb
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_recording.yml
Labels: bug, gaprindashvili/yes

#228 [GAPRINDASHVILI] Update translations for g update
  locale/es/ManageIQ_Providers_Ovirt.po
  locale/fr/ManageIQ_Providers_Ovirt.po
  locale/ja/ManageIQ_Providers_Ovirt.po
  locale/pt_BR/ManageIQ_Providers_Ovirt.po
  locale/zh_CN/ManageIQ_Providers_Ovirt.po
Labels: internationalization

#233 Use old refresh as default
  config/settings.yml
Labels: blocker, bug, gaprindashvili/yes
