Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2018-10, with the labels that each got.

#294 Fix PXE provisioning
  app/models/manageiq/providers/redhat/infra_manager/provision/configuration.rb
Labels: bug, hammer/yes

#296 Fix ISO provisioning with kickstart
  app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
  spec/models/manageiq/providers/redhat/infra_manager/provision/configuration_spec.rb
Labels: blocker, bug, hammer/yes

#297 Don't use interpolations in gettext strings
  app/models/manageiq/providers/redhat/infra_manager/provision_workflow.rb
Labels: hammer/yes, internationalization

#298 Fix attach_floppy to pass "floppy" type
  app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
  spec/models/manageiq/providers/redhat/infra_manager/provision/configuration_spec.rb
Labels: wip

#300 [WIP] Fix pxe provisioning
  app/models/manageiq/providers/redhat/infra_manager/provision/configuration.rb
Labels: bug, hammer/yes, wip

#302 [Changelog] Add Sprint 97 and Hammer Beta1 update
  CHANGELOG.md
Labels: documentation

#303 [HAMMER] [Changelog] Update for Hammer Beta2
  CHANGELOG.md
Labels: documentation
