Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2018-03, with the labels that each got.

#222 Fix spec tests without have_attributes extensions
  spec/models/manageiq/providers/redhat/infra_manager/event_catcher/runner_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/event_parser_spec.rb
Labels: test

#221 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-2
  CHANGELOG.md
Labels: documentation

#224 Provide max memory on VM reconfigure
  app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
  spec/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4_spec.rb
Labels: bug, gaprindashvili/yes

#215 [Changelog] Update for Sprint 79
  CHANGELOG.md
Labels: documentation

#231 Fix broken tests caused by fog-openstack upgrade
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_ovn_provider.yml
Labels: gaprindashvili/yes
