Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2018-11, with the labels that each got.

#305 [HAMMER] Add translations for hammer
  locale/es/ManageIQ_Providers_Ovirt.po
  locale/fr/ManageIQ_Providers_Ovirt.po
  locale/ja/ManageIQ_Providers_Ovirt.po
  locale/pt_BR/ManageIQ_Providers_Ovirt.po
  locale/zh_CN/ManageIQ_Providers_Ovirt.po
Labels: internationalization

#306 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-6
  CHANGELOG.md
Labels: documentation

#314 [HAMMER] Fix ovn recording for hammer branch
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_ovn_provider.yml
Labels: test

#310 No need to override disconnect_inv from core
  app/models/manageiq/providers/redhat/infra_manager/vm.rb
Labels: blocker, gaprindashvili/yes, hammer/yes, wip
