Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2018-09, with the labels that each got.

#284 Moving Inventory Builder functionality to Inventory
  app/models/manageiq/providers/redhat/builder.rb
  app/models/manageiq/providers/redhat/infra_manager/refresh/refresher.rb
  app/models/manageiq/providers/redhat/inventory.rb
  app/models/manageiq/providers/redhat/inventory/persister.rb
  app/models/manageiq/providers/redhat/network_manager/refresher.rb
Labels: cleanup

#285 Move ManagerRefresh to InventoryRefresh
  app/models/manageiq/providers/redhat/infra_manager/refresh/refresher.rb
Labels: refactoring

#286 [WIP] Use core's disconnect hook
  app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
Labels: wip

#275 Add sysprep support for ovirt
  app/models/manageiq/providers/redhat/infra_manager/provision/configuration.rb
  app/models/manageiq/providers/redhat/infra_manager/provision_workflow.rb
  spec/models/manageiq/providers/redhat/infra_manager/provision/configuration_spec.rb
Labels: enhancement

#290 [Changelog] Update for Sprint 95
  CHANGELOG.md
Labels: documentation

#291 [GAPRINDASHVILI] fix targeted refresh
  app/models/manageiq/providers/redhat/inventory/collector/target_collection.rb
  app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
  app/models/manageiq/providers/redhat/inventory/persister/target_collection.rb
  app/models/manageiq/providers/redhat/inventory_collection_default/infra_manager.rb
Labels: bug

#292 Add safe operator for bz 1633540 to protect against empty source_vms
  app/models/manageiq/providers/redhat/infra_manager/provision_workflow.rb
Labels: bug

#293 [HAMMER] [Changelog] Update for Hammer Beta-1 release
  CHANGELOG.md
Labels: documentation
