Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2018-08, with the labels that each got.

#253 [Changelog] Update for Sprint 86
  CHANGELOG.md
Labels: documentation

#276 Fix disk_type attribute
  app/models/manageiq/providers/redhat/infra_manager/refresh/parse/parser.rb
  app/models/manageiq/providers/redhat/infra_manager/refresh/parse/strategies/vm_inventory.rb
  app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_graph_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_vm_4_spec.rb
Labels: bug

#277 Fix provisioning independent VM
  app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
  app/models/manageiq/providers/redhat/infra_manager/provision/cloning.rb
  spec/models/manageiq/providers/redhat/infra_manager/provision_spec.rb
Labels: bug, gaprindashvili/yes

#283 Ovirt manager_ref is just [:uid_ems] which differs from core
  app/models/manageiq/providers/redhat/inventory.rb
  app/models/manageiq/providers/redhat/inventory/collector.rb
  app/models/manageiq/providers/redhat/inventory/parser.rb
  app/models/manageiq/providers/redhat/inventory/persister.rb
  app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_collections.rb
  app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_group/vms_collections.rb
Labels: bug

#280 Add support to set VM memory and number of CPUs
  app/models/manageiq/providers/redhat/infra_manager.rb
  spec/models/manageiq/providers/redhat/infra_manager_spec.rb
Labels: enhancement, gaprindashvili/yes

#281 [Changelog] Update for Sprint 93
  CHANGELOG.md
Labels: documentation

#282 Fix setting storage attributes during vm provision
  app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
  spec/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4_spec.rb
Labels: blocker, bug, gaprindashvili/yes
