Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2019-08, with the labels that each got.

#397 PGError does not exist anymore
  app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
  spec/models/manageiq/providers/redhat/infra_manager_spec.rb
Labels: bug

#398 [Changelog] Update for Ivanchuk Beta2
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#399 Refactor runner usage due to core refactoring
  app/models/manageiq/providers/redhat/ansible_role_workflow.rb
  spec/models/manageiq/providers/redhat/ansible_role_workflow_spec.rb
Labels: bug, ivanchuk/yes, refactoring

#394 Remove v3 api form SSA
  app/models/manageiq/providers/redhat/infra_manager/vm_or_template_shared/scanning.rb
  app/models/manageiq/providers/redhat/inventory/collector.rb
Labels: bug, ivanchuk/yes

#396 Define host as proper lazy object
  app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
Labels: bug

#400 Fix AnsibleRoleWorkflow spec
  spec/models/manageiq/providers/redhat/ansible_role_workflow_spec.rb
Labels: ivanchuk/yes, test
