Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2019-11, with the labels that each got.

#425 Subclass require_snapshot_for_scan? method
  app/models/manageiq/providers/redhat/infra_manager/vm_or_template_shared/scanning.rb
Labels: refactoring

#430 Add CODEOWNERS
  .github/CODEOWNERS
Labels: documentation

#432 Remove zanata from README
  README.md
Labels: cleanup

#433 update CODEOWNERS
  .github/CODEOWNERS
Labels: documentation

#431 Rely on the default implementation of .ems_class
  app/models/manageiq/providers/redhat/network_manager/event_catcher.rb
  app/models/manageiq/providers/redhat/network_manager/metrics_collector_worker.rb
  app/models/manageiq/providers/redhat/network_manager/refresh_worker.rb
Labels: refactoring

#434 Remove two unused methods
  app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
Labels: cleanup

#437 Subclass ResourcePools
  app/models/manageiq/providers/redhat/infra_manager.rb
  app/models/manageiq/providers/redhat/infra_manager/resource_pool.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_4_async_graph_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_network_spec.rb
Labels: refactoring

#435 Remove ems_ref_obj
  app/models/manageiq/providers/redhat/infra_manager/event_parser.rb
  app/models/manageiq/providers/redhat/infra_manager/vm/operations/relocation.rb
  app/models/manageiq/providers/redhat/infra_manager/vm_import.rb
  app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_4_async_graph_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_network_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/vm_import_spec.rb
Labels: cleanup
