Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2019-04, with the labels that each got.

#353 Fix removing a disk from a Vm
  app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
  spec/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4_spec.rb
Labels: blocker, bug, hammer/yes

#357 Update .travis.yml PostgreSQL version to 10
  .travis.yml
Labels: test

#358 [Changelog] Update for Hammer-5 release
  CHANGELOG.md
Labels: documentation

#359 Fix refreshing ipmi from host
  app/models/manageiq/providers/redhat/infra_manager/refresh/parse/parser.rb
  app/models/manageiq/providers/redhat/infra_manager/refresh/parse/strategies/host_inventory.rb
  app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_graph_target_host_spec.rb
Labels: bug, hammer/yes

#360 Use the host_geust_devices inventory collection
  app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
  app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_collections.rb
Labels: bug
