Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2019-07, with the labels that each got.

#385 Fix host ip address parsing
  app/models/manageiq/providers/redhat/infra_manager/refresh/parse/parser.rb
  app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_3_1_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_graph_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_spec.rb
  spec/spec_helper.rb
Labels: bug

#388 Disable all refreshes except graph refresh
  app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
  config/settings.yml
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresh_after_publish_vm_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_3_1_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_template_disconnect_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_vm_4_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_vm_spec.rb
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_publish_vm_to_template.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_target_template_disconnect.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_3_1.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_4_1.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_target_new_vm.yml
  tools/generate_refresh_template_spec.rb
  tools/refresher_v4_spec_generator_template.txt
Labels: cleanup

#390 Fix potential bug for graph refresh
  app/models/manageiq/providers/redhat/infra_manager.rb
Labels: bug, ivanchuk/yes

#392 [Changelog] Update for Ivanchuk Beta1
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#393 Remove old redhat refresh_parser
  app/models/manageiq/providers/redhat/network_manager.rb
  app/models/manageiq/providers/redhat/network_manager/refresh_parser.rb
Labels: bug

#395 Bump ovirt-engine-sdk version
  manageiq-providers-ovirt.gemspec
Labels: dependencies
