Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2019-01, with the labels that each got.

#329 Replace custom snapshot_parent saver
  app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
  app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_collections.rb
  app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_group/vms_collections.rb
  app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_group/vms_dependency_collections.rb
Labels: cleanup

#330 Remove duplicated persister shared_options
  app/models/manageiq/providers/redhat/inventory/persister.rb
Labels: refactoring

#327 [HAMMER] Bump hammer travis.yml to ruby 2.4.5
  .travis.yml
Labels: test

#331 Fix bug in vm targeted refresh
  app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_graph_target_vm_spec.rb
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_with_host.yml
Labels: blocker, bug, hammer/yes

#333 [Changelog] Update for Hammer-1
  CHANGELOG.md
Labels: documentation

#334 [Changelog] Update for Sprint 102
  CHANGELOG.md
Labels: documentation
