Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2019-03, with the labels that each got.

#346 mapping from "powering_up" to "on"
  app/models/manageiq/providers/redhat/infra_manager/vm.rb
Labels: bug

#347 [Changelog] Update for Sprint 106
  CHANGELOG.md
Labels: documentation

#348 Fix deleting a disk from VM
  app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
  spec/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4_spec.rb
Labels: blocker, bug, hammer/yes

#349 Remove references to MiqPassword
  app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
  spec/models/manageiq/providers/redhat/infra_manager_spec.rb
Labels: technical debt

#350 [Changelog] Update for Sprint 107
  CHANGELOG.md
Labels: documentation

#351 Update supported ruby versions on Travis
  .travis.yml
Labels: test

#352 [Changelog] Update for Hammer-4
  CHANGELOG.md
Labels: documentation
