Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2019-09, with the labels that each got.

#404 Fix specs - numeric only passwords
  spec/models/manageiq/providers/redhat/infra_manager/inventory/strategies/v4_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/ovirt_refresher_spec_common.rb
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_ovn_provider.yml
Labels: ivanchuk/yes, test

#405 Add a method for SSA
  app/models/manageiq/providers/redhat/inventory/collector.rb
Labels: blocker, bug, ivanchuk/yes

#406 Add supports_conversion_host to Vm
  app/models/manageiq/providers/redhat/infra_manager/vm.rb
  spec/models/manageiq/providers/redhat/infra_manager/vm_spec.rb
Labels: enhancement, ivanchuk/yes

#407 [Changelog] Rollup of Ivanchuk releases
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#410 [Changelog] Update for Sprint 120
  CHANGELOG.md
Labels: documentation
