Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2019-05, with the labels that each got.

#361 Simplify infra collection definitions
  app/models/manageiq/providers/redhat/inventory/persister.rb
  app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_collections.rb
  app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_group/cluster_collections.rb
  app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_group/datacenters_collections.rb
  app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_group/storagedomains_collections.rb
  app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_group/vms_collections.rb
  app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_group/vms_dependency_collections.rb
  app/models/manageiq/providers/redhat/inventory/persister/infra_manager.rb
  app/models/manageiq/providers/redhat/inventory/persister/target_collection.rb
Labels: cleanup

#364 Change plugin common methods to class methods
  lib/manageiq/providers/ovirt/engine.rb
Labels: refactoring

#363 Bump master travis.yml to ruby 2.4.6
  .travis.yml
Labels: test

#366 Update for Hammer-6
  CHANGELOG.md
Labels: documentation

#368 [HAMMER] Bump hammer travis.yml to ruby 2.4.6
  .travis.yml
Labels: test
