Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2019-02, with the labels that each got.

#336 Host targeted refresh deleting and re-creating storage, switch, and lan records
  app/models/manageiq/providers/redhat/inventory/collector/target_collection.rb
  app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_group/networks_collections.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/ovirt_refresher_spec_common.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_graph_target_host_spec.rb
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_host.yml
Labels: blocker, bug

#337 Revert "Fix disk_type attribute"
  app/models/manageiq/providers/redhat/infra_manager/refresh/parse/parser.rb
  app/models/manageiq/providers/redhat/infra_manager/refresh/parse/strategies/vm_inventory.rb
  app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_graph_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_target_vm_4_spec.rb
Labels: gaprindashvili/yes, hammer/yes

#339 Add ConversionHost and ServiceTemplateTransformationPlan subclasses
  app/models/manageiq/providers/redhat/infra_manager/conversion_host.rb
  app/models/manageiq/providers/redhat/infra_manager/service_template_transformation_plan.rb
Labels: enhancement

#340 [Changelog] Update for Sprint 105
  CHANGELOG.md
Labels: documentation

#341 Upgrade from FactoryGirl to FactoryBot
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_graph_target_host_spec.rb
  tools/refresher_v4_spec_generator_template.txt
Labels: test

#342 Fix sporadic test failure on sorting IDs
  spec/models/manageiq/providers/redhat/infra_manager/refresh/ovirt_refresher_spec_common.rb
Labels: bug/sporadic test failure, test

#344 [Changelog] Update for Hammer-3
  CHANGELOG.md
Labels: documentation, hammer/yes

#343 Skip VMs missing a cluster when saving relats
  app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
  app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_collections.rb
  app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_group/cluster_collections.rb
  app/models/manageiq/providers/redhat/inventory/persister/definitions/infra_group/vms_dependency_collections.rb
Labels: bug
