Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2020-07, with the labels that each got.

#507 Add applications requests to VCRs
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_lans_refresh_recording.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_host.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_template.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_template_with_host.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_after_full.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_deleted_snapshot.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_removal.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_with_host.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_recording.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_recording_custom_attrs.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_multi_datacenter_network_recording.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_network_ports_recording.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_reconfigure_with_no_restart_needed_recording.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_reconfigure_with_restart_needed_recording.yml
Labels: technical debt, test

#505 Set tools_status based on presence of ovirt-guest-agent application
  app/models/manageiq/providers/redhat/inventory/collector.rb
  app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_4_async_graph_spec.rb
Labels: enhancement

#511 Prefer Array.wrap over Object#to_miq_a
  app/models/manageiq/providers/redhat/inventory/collector/target_collection.rb
  app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
Labels: technical debt

#512 MiqHashStruct was replaced with OpenStruct in provisioning
  spec/models/manageiq/providers/redhat/infra_manager/provision_workflow_spec.rb
Labels: bug, test

#513 Add APP_PATH to allow using Rails directly
  bin/rails
Labels: developer, enhancement
