Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2020-02, with the labels that each got.

#463 External network registrations fix
  spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_4_async_graph_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_4_custom_attributes_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_network_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresher/response_yamls/external_network_providers.yml
  spec/models/manageiq/providers/redhat/infra_manager/refresher/response_yamls/external_network_providers_new.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_recording_custom_attrs.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_network_recording.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_ovn_provider.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_ovn_provider_1.yml
Labels: bug, test

#464 remove unused NetworkManager::MetricsCapture
  app/models/manageiq/providers/redhat/network_manager.rb
  app/models/manageiq/providers/redhat/network_manager/metrics_capture.rb
  app/models/manageiq/providers/redhat/network_manager/metrics_collector_worker.rb
  config/settings.yml
Labels: cleanup

#458 Html5 console disabled by default
  app/models/manageiq/providers/redhat/infra_manager/vm/remote_console.rb
  config/settings.yml
  spec/models/manageiq/providers/redhat/infra_manager/vm/remote_console_spec.rb
Labels: enhancement

#466 Ems metrics collector section should remain
  config/settings.yml
Labels: bug

#465 Code style cleanup
  spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_4_async_graph_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_network_spec.rb
Labels: cleanup

#467 OvirtSDK4 objects conversion to Hash
  app/models/manageiq/providers/redhat/infra_manager/event_parser.rb
  spec/models/manageiq/providers/redhat/infra_manager/event_parser_spec.rb
Labels: bug

#471 Add location for localfs storage
  app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
Labels: bug, hammer/yes, ivanchuk/yes

#476 Require manageiq-smartstate in VmOrTemplate::Scanning
  app/models/manageiq/providers/redhat/infra_manager/vm_or_template_shared/scanning.rb
Labels: bug

#470 [IVANCHUK] Fix VCR recording
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher/response_yamls/external_network_providers.yml
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher/response_yamls/external_network_providers_new.yml
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_4_async_graph_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_network_spec.rb
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_ovn_provider.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_ovn_provider_1.yml
Labels: test

#453 Allow user to set format and sparsity during provisioning and validate config
  app/models/manageiq/providers/redhat/infra_manager/provision/cloning.rb
  app/models/manageiq/providers/redhat/infra_manager/provision_workflow.rb
  app/models/manageiq/providers/redhat/infra_manager/provision_workflow/dialog_field_validation.rb
  app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
  spec/models/manageiq/providers/redhat/infra_manager/provision_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/provision_workflow/dialog_field_validation_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/provision_workflow_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_4_async_graph_spec.rb
Labels: enhancement
