Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2020-09, with the labels that each got.

#519 [JANSA] Fix network spec VCR
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_network_recording.yml
Labels: test

#518 Look for qemu-guest-agent for tools status as well
  app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
Labels: enhancement

#520 [IVANCHUK] VCR spec fixes
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_lans_refresh_recording.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_host.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_template.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_template_with_host.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_after_full.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_deleted_snapshot.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_removal.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_with_host.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_recording.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_recording_custom_attrs.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_network_recording.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_reconfigure_with_no_restart_needed_recording.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_reconfigure_with_restart_needed_recording.yml
Labels: technical debt, test

#517 Update DDF schema to version 2
  app/models/manageiq/providers/redhat/infra_manager.rb
Labels: enhancement

#521 Rename textarea-field to textarea in the DDF provider form
  app/models/manageiq/providers/redhat/infra_manager.rb
Labels: bug

#524 Sync the tenant_id when creating a NetworkManager
  app/models/manageiq/providers/redhat/infra_manager.rb
Labels: bug

#525 Make the default credentials required in the provider DDF
  app/models/manageiq/providers/redhat/infra_manager.rb
Labels: bug

#527 Prefer ManageIQ::Password over legacy MiqPassword constant
  app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
Labels: enhancement
