Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2020-01, with the labels that each got.

#446 Subclass VmScan job as ManageIQ::Providers::Redhat::InfraManager::Scanning::Job
  app/models/manageiq/providers/redhat/infra_manager/scanning.rb
  app/models/manageiq/providers/redhat/infra_manager/scanning/job.rb
  app/models/manageiq/providers/redhat/infra_manager/vm_or_template_shared/scanning.rb
Labels: refactoring, smart state

#454 Subclass InfraManager metrics capture
  app/models/manageiq/providers/redhat/infra_manager/metrics_capture.rb
  spec/models/manageiq/providers/redhat/infra_manager/metrics_capture_spec.rb
Labels: bug

#452 Native viewer support
  app/models/manageiq/providers/redhat/infra_manager/ovirt_services.rb
  app/models/manageiq/providers/redhat/infra_manager/vm/remote_console.rb
  spec/models/manageiq/providers/redhat/infra_manager/vm/remote_console_spec.rb
Labels: enhancement

#457 Fix for NICs that don't have a vnic_profile
  app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
Labels: bug

#455 [IVANCHUK] Remodel to add networks by external providers
  app/models/manageiq/providers/redhat/infra_manager.rb
  app/models/manageiq/providers/redhat/infra_manager/external_distributed_virtual_switch.rb
  app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
  app/models/manageiq/providers/redhat/inventory/collector/target_collection.rb
  app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
  app/models/manageiq/providers/redhat/inventory/persister/infra_manager.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/ovirt_refresher_spec_common.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher/response_yamls/external_network_providers_new.yml
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_graph_target_vm_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_network_spec.rb
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_template.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_template_with_host.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_after_full.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_deleted_snapshot.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_removal.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_with_host.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_network_recording.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_ovn_provider_1.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_reconfigure_with_no_restart_needed_recording.yml
  spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_reconfigure_with_restart_needed_recording.yml
Labels: bug, enhancement

#459 Avoid a new OvirtServices instantiation
  app/models/manageiq/providers/redhat/infra_manager.rb
Labels: refactoring

#462 Don't check for Datacenter class
  app/models/manageiq/providers/redhat/infra_manager/event_parser.rb
Labels: bug
