Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2020-06, with the labels that each got.

#500 Remove RestClient
  app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
  spec/models/manageiq/providers/redhat/infra_manager_spec.rb
Labels: bug

#496 [IVANCHUK] Vm disk resize
  app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
  app/models/manageiq/providers/redhat/infra_manager/vm.rb
  app/models/manageiq/providers/redhat/infra_manager/vm/reconfigure.rb
  spec/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/vm/reconfigure_spec.rb
Labels: enhancement

#502 Add cpu_affinity for vms
  app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
Labels: enhancement

#503 Update cpu affinity to include both virtual and host cpu
  app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
Labels: enhancement

#506 Set the monitor_running event to unblock the main thread
  app/models/manageiq/providers/redhat/infra_manager/event_catcher/runner.rb
Labels: bug, jansa/yes?
