Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2020-05, with the labels that each got.

#493 Fix README to point to travis-ci.com instead of travis-ci.org
  README.md
Labels: bug, developer

#494 Removing deprecated Gemnasium badge
  README.md
Labels: developer

#497 Add supports terminate feature
  app/models/manageiq/providers/redhat/infra_manager/vm/operations.rb
  spec/models/manageiq/providers/redhat/infra_manager/vm_spec.rb
Labels: bug, jansa/yes?
