Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2020-03, with the labels that each got.

#479 Fix constant redefinition warnings in specs
  spec/models/manageiq/providers/redhat/infra_manager/refresher/refresh_recording_modifier_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_graph_target_template_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_graph_target_vm_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_huge_async_spec.rb
Labels: refactoring, test

#477 Add network reconfiguration
  app/models/manageiq/providers/redhat/infra_manager/ovirt_services.rb
  app/models/manageiq/providers/redhat/infra_manager/vm.rb
  app/models/manageiq/providers/redhat/infra_manager/vm/reconfigure.rb
  spec/factories/datacenter.rb
  spec/factories/switch.rb
  spec/models/manageiq/providers/redhat/infra_manager/ovirt_services/v4_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/vm/reconfigure_spec.rb
Labels: enhancement

#482 Provision workflow fix
  app/models/manageiq/providers/redhat/infra_manager/ovirt_services.rb
  spec/models/manageiq/providers/redhat/infra_manager/provision_workflow_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_network_spec.rb
Labels: enhancement

#483 Vm disk resize
  app/models/manageiq/providers/redhat/infra_manager/ovirt_services.rb
  app/models/manageiq/providers/redhat/infra_manager/vm.rb
  app/models/manageiq/providers/redhat/infra_manager/vm/reconfigure.rb
  spec/models/manageiq/providers/redhat/infra_manager/ovirt_services/v4_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/vm/reconfigure_spec.rb
Labels: enhancement

#484 [IVANCHUK] Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#485 [JANSA] Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#486 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#489 Updates for Sprint 133
  CHANGELOG.md
Labels: documentation
