Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2020-10, with the labels that each got.

#528 [IVANCHUK] Native viewer support
  app/models/manageiq/providers/redhat/infra_manager/ovirt_services/strategies/v4.rb
  app/models/manageiq/providers/redhat/infra_manager/vm/remote_console.rb
  spec/models/manageiq/providers/redhat/infra_manager/vm/remote_console_spec.rb
Labels: enhancement

#531 Test with ruby 2.5.8 and 2.6.6
  .travis.yml
Labels: test

#495 Switch to manageiq-style
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
  manageiq-providers-ovirt.gemspec
Labels: developer, unmergeable

#533 Fix .rubocop_local.yml
  .rubocop_local.yml
Labels: developer

#538 Bump ovirt-engine-sdk to 4.4.0
  manageiq-providers-ovirt.gemspec
Labels: dependencies
