Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2021-12, with the labels that each got.

#582 Fix default api verification always succeeding
  app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
Labels: bug, lasker/yes?, morphy/yes?

#581 Fix metrics_endpoint info not passed to check_connect_metrics
  app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
Labels: bug, lasker/yes?, morphy/yes?

#583 Move ovirt_metrics gem to ovirt gemspec
  manageiq-providers-ovirt.gemspec
Labels: cleanup

#586 Targeted refresh should default to enabled
  config/settings.yml
Labels: bug, lasker/yes?, morphy/yes?

#587 converting supported_for_create to supports :create
  app/models/manageiq/providers/redhat/infra_manager.rb
Labels: enhancement

#588 Fix ems_custom_fields manager_ref
  app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
Labels: bug
