Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2021-03, with the labels that each got.

#551 Fix metrics connection setup failure
  app/models/manageiq/providers/redhat/infra_manager/api_integration.rb
  spec/models/manageiq/providers/redhat/infra_manager_spec.rb
Labels: bug, kasparov/yes?

#552 Don't manually set miq_template's model_class
  app/models/manageiq/providers/redhat/inventory/persister/infra_manager.rb
Labels: refactoring

#555 Test with ruby 2.6.6 and 2.7.2 per ManageIQ/manageiq#19678
  .travis.yml
Labels: test

#547 Add systemd unit files for workers
  build/systemd_units/manageiq-providers-redhat_infra_manager_event_catcher.target
  build/systemd_units/manageiq-providers-redhat_infra_manager_event_catcher@.service
  build/systemd_units/manageiq-providers-redhat_infra_manager_metrics_collector.target
  build/systemd_units/manageiq-providers-redhat_infra_manager_metrics_collector@.service
  build/systemd_units/manageiq-providers-redhat_infra_manager_refresh.target
  build/systemd_units/manageiq-providers-redhat_infra_manager_refresh@.service
  build/systemd_units/manageiq-providers-redhat_network_manager_event_catcher.target
  build/systemd_units/manageiq-providers-redhat_network_manager_event_catcher@.service
  build/systemd_units/manageiq-providers-redhat_network_manager_refresh.target
  build/systemd_units/manageiq-providers-redhat_network_manager_refresh@.service
Labels: technical debt
