Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2022-12, with the labels that each got.

#621 Subclass IsoDatastore and transfer from core
  app/models/manageiq/providers/ovirt/infra_manager.rb
  app/models/manageiq/providers/ovirt/infra_manager/iso_datastore.rb
  app/models/manageiq/providers/ovirt/infra_manager/ovirt_services.rb
  app/models/manageiq/providers/ovirt/inventory/collector/infra_manager.rb
  app/models/manageiq/providers/ovirt/inventory/collector/target_collection.rb
  app/models/manageiq/providers/ovirt/inventory/parser/infra_manager.rb
  app/models/manageiq/providers/ovirt/inventory/persister/infra_manager.rb
  spec/factories/iso_datastore.rb
  spec/models/manageiq/providers/ovirt/infra_manager/iso_datastore_spec.rb
  spec/models/manageiq/providers/ovirt/infra_manager/ovirt_services/v4_spec.rb
  spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/ovirt_lans_refresh_recording.yml
  spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/ovirt_sdk_refresh_graph_target_host.yml
  spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/ovirt_sdk_refresh_graph_target_template.yml
  spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/ovirt_sdk_refresh_graph_target_template_with_host.yml
  spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_after_full.yml
  spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_deleted_snapshot.yml
  spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_removal.yml
  spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_with_host.yml
  spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/ovirt_sdk_refresh_recording.yml
  spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/ovirt_sdk_refresh_recording_custom_attrs.yml
  spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/refresher_multi_datacenter_network_recording.yml
  spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/refresher_network_ports_recording.yml
  spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/refresher_reconfigure_with_no_restart_needed_recording.yml
  spec/vcr_cassettes/manageiq/providers/ovirt/infra_manager/refresh/refresher_reconfigure_with_restart_needed_recording.yml
Labels: enhancement

#626 Remove Red Hat Copyright notice
  app/models/manageiq/providers/ovirt/connection_manager.rb
  spec/models/manageiq/providers/ovirt/connection_manager_spec.rb
Labels: documentation, technical debt

#623 Fix RHV `#find_destination_in_vmdb` looking for the wrong type
  app/models/manageiq/providers/ovirt/infra_manager/provision/cloning.rb
Labels: bug, oparin/yes?
