Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2022-02, with the labels that each got.

#591 Allow minor relases of ovirt_metrics such as 3.1 for rails 6.1 support
  manageiq-providers-ovirt.gemspec
Labels: dependencies, rails6.1

#592 Switch to GitHub Actions
  .github/workflows/ci.yaml
  .travis.yml
  README.md
  bin/before_install
  bin/ci/after_script
  bin/setup
  manageiq-providers-ovirt.gemspec
Labels: developer, test

#593 Add Build History Graph to README.md
  README.md
Labels: developer, test

#594 Replace deprecated method .parent for rails 6.1
  spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_4_async_graph_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_4_custom_attributes_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_lans_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_multi_datacenter_network_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_network_ports_spec.rb
  spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_network_spec.rb
Labels: rails6.1

#596 Add supports iso datastore
  app/models/manageiq/providers/redhat/infra_manager.rb
Labels: enhancement

#597 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: developer, test
