Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2023-03, with the labels that each got.

#633 Fix passing custom CA cert via DDF params
  app/models/manageiq/providers/ovirt/infra_manager/api_integration.rb
  spec/models/manageiq/providers/ovirt/infra_manager_spec.rb
Labels: bug, oparin/yes?, petrosian/yes?

#637 Fix VM Reconfigure for stopped VMs
  app/models/manageiq/providers/ovirt/infra_manager/vm/reconfigure.rb
  spec/models/manageiq/providers/ovirt/infra_manager/vm/reconfigure_spec.rb
Labels: bug, petrosian/yes?

#632 Remove the OVN NetworkManager Event Catcher
  app/models/manageiq/providers/ovirt/network_manager.rb
  app/models/manageiq/providers/ovirt/network_manager/event_catcher.rb
  app/models/manageiq/providers/ovirt/network_manager/event_catcher/runner.rb
  app/models/manageiq/providers/ovirt/network_manager/event_parser.rb
  config/settings.yml
  spec/models/manageiq/providers/ovirt/infra_manager/refresher/refresher_4_async_graph_spec.rb
  systemd/manageiq-providers-ovirt_network_manager_event_catcher.target
  systemd/manageiq-providers-ovirt_network_manager_event_catcher@.service
Labels: bug, petrosian/yes?

#638 Add Missing Protocol to Native Console API Response
  app/models/manageiq/providers/ovirt/infra_manager/vm/remote_console.rb
Labels: enhancement

#639 Adding Enabled / Disabled field
  app/models/manageiq/providers/ovirt/infra_manager/host.rb
Labels: enhancement
