Repository ManageIQ/manageiq-providers-ovirt, pull requests merged in 2024-02, with the labels that each got.

#656 Drop require_nested and include_concern
  app/models/manageiq/providers/ovirt/infra_manager.rb
  app/models/manageiq/providers/ovirt/infra_manager/event_catcher.rb
  app/models/manageiq/providers/ovirt/infra_manager/metrics_collector_worker.rb
  app/models/manageiq/providers/ovirt/infra_manager/provision.rb
  app/models/manageiq/providers/ovirt/infra_manager/provision/configuration.rb
  app/models/manageiq/providers/ovirt/infra_manager/provision_via_iso.rb
  app/models/manageiq/providers/ovirt/infra_manager/provision_via_pxe.rb
  app/models/manageiq/providers/ovirt/infra_manager/provision_workflow.rb
  app/models/manageiq/providers/ovirt/infra_manager/refresh_worker.rb
  app/models/manageiq/providers/ovirt/infra_manager/scanning.rb
  app/models/manageiq/providers/ovirt/infra_manager/template.rb
  app/models/manageiq/providers/ovirt/infra_manager/vm.rb
  app/models/manageiq/providers/ovirt/infra_manager/vm/operations.rb
  app/models/manageiq/providers/ovirt/infra_manager/vm_or_template_shared.rb
  app/models/manageiq/providers/ovirt/inventory.rb
  app/models/manageiq/providers/ovirt/inventory/collector.rb
  app/models/manageiq/providers/ovirt/inventory/parser.rb
  app/models/manageiq/providers/ovirt/inventory/persister.rb
  app/models/manageiq/providers/ovirt/network_manager.rb
  app/models/manageiq/providers/ovirt/network_manager/cloud_network.rb
  app/models/manageiq/providers/ovirt/network_manager/refresh_worker.rb
Labels: technical debt, rails7

#657 Set minimum version to support rails 7
  manageiq-providers-ovirt.gemspec
Labels: rails7

#659 drop use of unuspported_reason_add
  app/models/manageiq/providers/ovirt/infra_manager.rb
  app/models/manageiq/providers/ovirt/infra_manager/host.rb
  app/models/manageiq/providers/ovirt/infra_manager/template.rb
  app/models/manageiq/providers/ovirt/infra_manager/vm.rb
  app/models/manageiq/providers/ovirt/infra_manager/vm/operations.rb
  app/models/manageiq/providers/ovirt/infra_manager/vm/operations/guest.rb
  app/models/manageiq/providers/ovirt/infra_manager/vm/operations/snapshot.rb
  app/models/manageiq/providers/ovirt/infra_manager/vm_or_template_shared/scanning.rb
Labels: refactoring

#660 [RADJABOV] Test radjabov with ruby 3.1
  .github/workflows/ci.yaml
Labels: test, ruby3.1
